name: sirrkothay
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.3.8
  image_picker: ^0.8.4+4
  path_provider: ^2.0.2
  path: ^1.8.0
  shared_preferences: ^2.0.6
  email_validator: ^2.0.1
  qr_flutter: ^4.0.0
  permission_handler: ^11.0.1

  flutter_launcher_icons: ^0.13.1
  cross_file: ^0.3.4+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  image_path: "assets/sirkothayLogo.png"
  android: "launcher_icon"
  ios: true

flutter:
  uses-material-design: true
  assets:
      - assets/
      - assets/fonts/
      